// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
  
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF37gxqirrO82u3DfLOVpassLcg5b9KUE',
    appId: '1:478118410168:android:015bef1f7105314e77814d',
    messagingSenderId: '478118410168',
    projectId: 'smartsacco-df4ce',
    storageBucket: 'smartsacco-df4ce.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9EMnX2KYB0qe2xRNcTT7iT7rG1hgiic',
    appId: '1:478118410168:ios:e3721e94c50158f577814d',
    messagingSenderId: '478118410168',
    projectId: 'smartsacco-df4ce',
    storageBucket: 'smartsacco-df4ce.firebasestorage.app',
    iosBundleId: 'com.example.smartloanSacco',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9EMnX2KYB0qe2xRNcTT7iT7rG1hgiic',
    appId: '1:478118410168:ios:38b69c3067d3978177814d',
    messagingSenderId: '478118410168',
    projectId: 'smartsacco-df4ce',
    storageBucket: 'smartsacco-df4ce.firebasestorage.app',
    iosBundleId: 'com.example.smartsacco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_CropfRkSoTzv6EYy4Oc0tKkxQXw3nU',
    appId: '1:478118410168:web:9f53b773ffb6f0e777814d',
    messagingSenderId: '478118410168',
    projectId: 'smartsacco-df4ce',
    authDomain: 'smartsacco-df4ce.firebaseapp.com',
    storageBucket: 'smartsacco-df4ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_CropfRkSoTzv6EYy4Oc0tKkxQXw3nU',
    appId: '1:478118410168:web:9f53b773ffb6f0e777814d',
    messagingSenderId: '478118410168',
    projectId: 'smartsacco-df4ce',
    authDomain: 'smartsacco-df4ce.firebaseapp.com',
    storageBucket: 'smartsacco-df4ce.firebasestorage.app',
  );

}